// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8YuauST5SDo-oz1Q8h9DGKAVAHNQt7nc',
    appId: '1:587336408810:web:08872e16457c40c88e0193',
    messagingSenderId: '587336408810',
    projectId: 'yama-motivate-app',
    authDomain: 'yama-motivate-app.firebaseapp.com',
    databaseURL: 'https://yama-motivate-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yama-motivate-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUCLxm2S8V2gzPD2oBmXM6bk_37oek8j4',
    appId: '1:587336408810:android:f7675345d081000b8e0193',
    messagingSenderId: '587336408810',
    projectId: 'yama-motivate-app',
    databaseURL: 'https://yama-motivate-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yama-motivate-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJxspiLlfNidSYD8C7Z9m9Zih1D3MpaL0',
    appId: '1:587336408810:ios:a3de796b3116fe6b8e0193',
    messagingSenderId: '587336408810',
    projectId: 'yama-motivate-app',
    databaseURL: 'https://yama-motivate-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yama-motivate-app.appspot.com',
    iosClientId: '587336408810-hsnhn8r36l3ruolp0f2jn4b8fctu0n03.apps.googleusercontent.com',
    iosBundleId: 'com.garlictech.yamaMotivate',
  );
}
