// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2x93Mfvz8GfB9CkG1DWIYIq9EXLebEHw',
    appId: '1:613858852311:android:0ab0c94f2c5b7e56e49f92',
    messagingSenderId: '613858852311',
    projectId: 'yet-another-projects',
    storageBucket: 'yet-another-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkgIJd8uM3kY5V1cpngB7LqX8KeFWjsLo',
    appId: '1:613858852311:ios:ee7a52ff28e57cdbe49f92',
    messagingSenderId: '613858852311',
    projectId: 'yet-another-projects',
    storageBucket: 'yet-another-projects.appspot.com',
    androidClientId: '613858852311-h4aid8pbdhp4qcvejahl7qf76ct4fcbn.apps.googleusercontent.com',
    iosClientId: '613858852311-6affg7hflckj4tnksjvt9h72kr19hcjd.apps.googleusercontent.com',
    iosBundleId: 'com.garlictech.yaha2',
  );
}
