org: garlictech
service: yaha
configValidationMode: error

plugins:
  - serverless-bundle
  - serverless-offline

package:
  individually: true
  patterns:
    - '!.build/**'
    - '!.git/**'
    - '!.serverless/**'
    - '!cdk.out/**'

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Name of the SST app that's deploying our infrastructure
  sstApp: ${self:custom.stage}-yaha
  bundle:
    packager: yarn
    linting: false
    sourcemaps: true
    caching: true
    esbuild: true

  offline:
    useChildProcesses: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  stack-seeder:
    handler: lib/lambda/stack-seeder/index.handler

  amplify-resolvers:
    handler: lib/lambda/amplify-resolvers/index.handler

  yaha-api-updater:
    handler: lib/lambda/yaha-api-updater/index.handler
