org: garlictech
service: common-backend
configValidationMode: error

plugins:
  - serverless-bundle
  - serverless-offline

package:
  individually: true

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Name of the SST app that's deploying our infrastructure
  sstApp: common-backend
  bundle:
    packager: yarn
    linting: false
    sourcemaps: true
    caching: true
    esbuild: true

  offline:
    useChildProcesses: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
