FROM cirrusci/flutter:3.3.1

RUN flutter doctor

RUN  sdkmanager "platform-tools" "platforms;android-29" "emulator" "system-images;android-29;default;x86" \
  && echo "no" | avdmanager --verbose create avd --force --name "int_test" --package "system-images;android-29;default;x86" --tag "default" --abi "x86"
