targets:
  $default:
    sources:
      - graphql/**
      - lib/**
      - $package$
    builders:
      json_serializable:
        options:
          include_if_null: false
          explicit_to_json: true
          checked: false
