projects:
  yaha:
    schemaPath: amplify/backend/api/yaha/build/schema.graphql
    includes:
      - ../../libs/gql-api/src/lib/generated/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ../../libs/gql-api/src/lib/generated/yaha-api.ts
        docsFilePath: ../../libs/gql-api/src/lib/generated/graphql
        region: us-east-1
        apiId: null
        maxDepth: 4
extensions:
  amplify:
    version: 3
