# include: package:effective_dart/analysis_options.yaml

include: package:flutter_lints/flutter.yaml
analyzer:
  exclude: [build/**, lib/**.g.dart, lib/models/**]
  strong-mode:
    implicit-casts: true
linter:
  rules:
