targets:
  $default:
    sources:
      - graphql/**
      - lib/$lib$
      - lib/models/**
      - $package$
    builders:
      # json_serializable:
      #   options:
      #     include_if_null: false
      #     # explicit_to_json: true
      #     # checked: false
      artemis:
        options:
          schema_mapping:
            # Schema mapping for CRUD
            - schema: graphql/crud-api-schema.graphql
              queries_glob: graphql/**.graphql
              output: lib/graphql/generated/api.dart
              naming_scheme: pathedWithTypes

            # Schema mapping for Flutter tests
            - schema: graphql/crud-api-schema.graphql
              queries_glob: graphql/test/**.graphql
              output: lib/../test/graphql/generated/api.dart
              naming_scheme: pathedWithTypes
          scalar_mapping:
            - custom_parser_import: 'package:fa_prev/graphql/utils/graphql_coercers.dart'
              graphql_type: AWSDateTime
              dart_type: DateTime
          generate_helpers: true
