name: yaha
description: Yet another hiking app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_yaha_lib:
    path: ../../libs/flutter/yaha-lib

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/icon@3x.png
  remove_alpha_ios: true

flutter_native_splash:
  background_image: assets/images/splash-screen.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

dev_dependencies:
  test: ^1.24.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
