name: yama
description: Yet another motivating app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  yama_lib:
    path: ../../libs/flutter/yama-lib

  revenuecat_purchase:
    path: ../../libs/flutter/revenuecat_purchase

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icon/

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/icon/appicon.png'
